### ISSUE TITLE
Unrelated to the repo, question about your Jappa Lucky Block Resource Pack

### ISSUE THREAD

**Issue by legendary-creeper** [KirbyKid256/BBCharter#15]
### Describe the feature you'd like to see

Hey, I tried to find a way to get in touch with you. I have a copyright-related question about your [Jappa Lucky Block Resource Pack](https://www.curseforge.com/minecraft/texture-packs/jappa-lucky-block) on CurseForge and would appreciate it if you could contact me on Discord at legendary_creeper. Ty!

**Comment by KirbyKid256** [comment]
Wild way to try to contact me by the way considering this is a tool for a porn game. But yeah thanks for letting me know
